[package]
name = "strinject"
version = "0.1.2"
edition = "2021"
description = "Inject text from somewhere else into given text"
repository = "https://github.com/Vrixyz/strinject"
license = "MIT OR Apache-2.0"
keywords = ["text", "automation", "string"]

[dependencies]
regex = "1.10"
